In [3]:
import torch

## 数据类型

In [6]:
# 类型
a = torch.randn(2, 3)  # shape is [2, 3]

print(a.type())
print(type(a))
print(isinstance(a, torch.FloatTensor))

torch.FloatTensor
<class 'torch.Tensor'>
True


In [7]:
print(isinstance(a, torch.cuda.FloatTensor))  # 数据是 cpu 类型的

a = a.cuda()  # 把数据变为 gpu 类型
print(isinstance(a, torch.cuda.FloatTensor))

False
True


### 标量

In [8]:
a = torch.tensor(1)
print(a)

b = torch.tensor(1.300)
print(b)

tensor(1)
tensor(1.3000)


### 看 dim
dim 和 shape 的区别：一个 [2, 3] 的 tensor，它的 shape 是 (2, 3)，它的 dim 是 2.

In [12]:
a = torch.tensor(2.5)
a.shape, len(a.shape), a.size()

(torch.Size([]), 0, torch.Size([]))

In [13]:
a = torch.randn(2, 3)
a.shape, len(a.shape), a.size()

(torch.Size([2, 3]), 2, torch.Size([2, 3]))

In [15]:
a = torch.tensor([2.3, 1.])
a, a.shape, len(a.shape), a.size()

(tensor([2.3000, 1.0000]), torch.Size([2]), 1, torch.Size([2]))

In [17]:
b = torch.FloatTensor([1])
c = torch.FloatTensor([2, 3])

b, c

(tensor([1.]), tensor([2., 3.]))

In [18]:
import numpy as np

data = np.ones(2)

a = torch.from_numpy(data)

data, a

(array([1., 1.]), tensor([1., 1.], dtype=torch.float64))

In [19]:
a = torch.ones(2)
a

tensor([1., 1.])

In [20]:
a = torch.zeros(2)
a

tensor([0., 0.])

In [22]:
# shape 和 size 都可以索引
a = torch.rand([2, 3])  # rand 和 randn，随机均匀分布，和随机正态分布

a, a.shape[0], a.shape[1], a.size(0), a.size(1)

(tensor([[0.8822, 0.4626, 0.6545],
         [0.8265, 0.5604, 0.1371]]),
 2,
 3,
 2,
 3)

In [23]:
# list 可以直接返回一个 list

a = torch.randn([2, 3, 4])
list(a.shape)

[2, 3, 4]

### 得到 tensor 数据的大小

In [27]:
a = torch.randn(2, 3, 28, 28)

a.numel(), a.dim()  # numel() 返回 tensor 占的内存

(4704, 4)

## 创建 tensor

In [28]:
# 从 numpy 中转换

a = np.array([2, 3.3])
b = torch.from_numpy(a)

c = np.ones([2, 3])
d = torch.from_numpy(c)

b, d

(tensor([2.0000, 3.3000], dtype=torch.float64),
 tensor([[1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64))

In [29]:
# 从 list 中转换

list = [2, 3, 4]
a = torch.tensor(list)

a

tensor([2, 3, 4])

### 创建未初始化的 tensor

In [30]:
a = torch.empty([2, 3])
a

tensor([[6.7406e+22, 2.6540e-09, 2.0804e+23],
        [1.6764e+22, 6.7703e+22, 5.4883e-05]])

### 创建随机 tensor

In [32]:
a = torch.randn([3, 2, 5])

b = torch.rand_like(a)

b.shape

torch.Size([3, 2, 5])

In [33]:
a = torch.randint(1, 10, [3, 3])  # 生成的 tensor 范围：[1, 10), shape 为 [3, 3]

a

tensor([[9, 9, 9],
        [2, 2, 9],
        [4, 2, 5]])

In [39]:
# 自定义均值和方差

a = torch.normal(mean=torch.full([10], 0.), std=torch.arange(1, 0., -0.1))
a

tensor([ 0.9925, -0.9006, -0.5114, -0.4418, -0.3699, -0.0488,  0.5707, -0.5671,
        -0.1098, -0.0755])

### torch.full

In [40]:
torch.full([2, 3], 5)  # 把 tensor 全赋值为 5

tensor([[5, 5, 5],
        [5, 5, 5]])

In [41]:
torch.full([], 7.)

tensor(7.)

### torch.arange

In [42]:
a = torch.arange(1, 10)
b = torch.arange(1, 10, 2)

a, b

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 3, 5, 7, 9]))

### linspace/logspace

In [44]:
a = torch.linspace(0, 10, steps=4)  # 把 1~10 分为 4 份
b = torch.linspace(0, 10, steps=11)

a, b

(tensor([ 0.0000,  3.3333,  6.6667, 10.0000]),
 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [50]:
a = torch.logspace(0, 1, steps=10)  # 把 0~1 分为 10 份，然后返回 10^i
b = torch.logspace(0, -1, steps=10)

a, b

(tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
          7.7426, 10.0000]),
 tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
         0.1000]))

### ones, zeros, eye

In [52]:
torch.ones([3, 3]), torch.zeros([2, 3])

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [55]:
torch.eye(2, 3), torch.eye(3)  # 对角线是 1

(tensor([[1., 0., 0.],
         [0., 1., 0.]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

### 随机打散

In [56]:
torch.randperm(10)

tensor([4, 3, 5, 7, 9, 0, 2, 1, 8, 6])

## tensor 索引与切片

In [4]:
a = torch.randn(4, 3, 28, 28)

a[0].shape, a[0, 0].shape, a[0, 0, 0, 0]

(torch.Size([3, 28, 28]), torch.Size([28, 28]), tensor(0.0545))

### 取连续的图片

In [6]:
a = torch.rand(4, 3, 28, 28)

a[:2, :1, :, :].shape

torch.Size([2, 1, 28, 28])

### 隔行采样

In [7]:
a = torch.rand(4, 3, 28, 28)

a[:, :, 0:28:2, 0:28:2].shape

torch.Size([4, 3, 14, 14])

### 选取指定的 index

In [18]:
a = torch.randn(4, 3, 28, 28)

# 第一个参数是要操作的维度，第二个参数是 index
a.index_select(0, torch.tensor([2, 3])).shape, a.index_select(3, torch.arange(10)).shape

(torch.Size([2, 3, 28, 28]), torch.Size([4, 3, 28, 10]))

### ...

In [19]:
a = torch.randn(4, 3, 28, 28)

a[...].shape, a[1, ...].shape, a[:, 1, ...].shape, a[..., :2].shape

(torch.Size([4, 3, 28, 28]),
 torch.Size([3, 28, 28]),
 torch.Size([4, 28, 28]),
 torch.Size([4, 3, 28, 2]))

### 通过 mask 索引

In [20]:
x = torch.randn([3, 4])

x

tensor([[-1.1231, -0.7375,  0.4064,  0.7017],
        [ 0.7530, -1.5781,  0.7586,  0.4149],
        [-1.9955,  0.0544, -1.0234,  1.4162]])

In [21]:
mask = x.ge(0.5)  # 大于 0.5 的为 true，否则为 false

mask

tensor([[False, False, False,  True],
        [ True, False,  True, False],
        [False, False, False,  True]])

In [23]:
torch.masked_select(x, mask)  # 这个方法会把 tensor 打平

tensor([0.7017, 0.7530, 0.7586, 1.4162])

### 通过 take 取元素

In [30]:
src = torch.tensor([[1, 2, 3], [4, 5, 6]])

src

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
torch.take(src, torch.tensor([0, 2, 3, 5]))  # 这个操作会先打平，再取元素

tensor([1, 3, 4, 6])

## 维度变换

### view /  reshape

In [34]:
a = torch.rand([4, 1, 28, 28])

a.view(4, -1).shape, a.reshape(4*28*28).shape

(torch.Size([4, 784]), torch.Size([3136]))

### unsqueeze

In [37]:
a = torch.randn([4, 1, 28, 28])

a.unsqueeze(0).shape, a.unsqueeze(-3).shape  # 增加一个维度，如果索引为正，在索引前插入；如果索引为负，在索引后插入

(torch.Size([1, 4, 1, 28, 28]), torch.Size([4, 1, 1, 28, 28]))

In [41]:
x = torch.tensor([1.2, 2.3])

x.unsqueeze(-1), x.unsqueeze(0)

(tensor([[1.2000],
         [2.3000]]),
 tensor([[1.2000, 2.3000]]))

### squeeze

In [42]:
b = torch.rand([1, 32, 1, 1])

b.squeeze(0).shape, b.squeeze(1).shape, b.squeeze(-1).shape  # 把维度为 1 的挤压掉

(torch.Size([32, 1, 1]), torch.Size([1, 32, 1, 1]), torch.Size([1, 32, 1]))

### expand & repeat

In [47]:
a = torch.rand([1, 32, 1, 1])

a.expand(4, 32, 14, 14).shape, a.expand(-1, 32, -1, -1).shape  # 扩展 tensor，-1 表示不变

(torch.Size([4, 32, 14, 14]), torch.Size([1, 32, 1, 1]))

In [49]:
b = torch.rand([1, 32 ,1, 1])

b.repeat(4, 1, 14, 14).shape  # repeat 中参数表示该维度要复制的次数，1 表示不复制

torch.Size([4, 32, 14, 14])

### 转置

In [5]:
a = torch.randn([3, 4])

a.t().shape

torch.Size([4, 3])

In [6]:
a = torch.randn([4, 3, 14, 14])

a.transpose(1, 3).shape  # 维度 1 和 3 交换

torch.Size([4, 14, 14, 3])

### 转置与恢复

有时需要恢复转置后的数据为原来的数据

In [13]:
a = torch.rand([4, 3, 32, 32])

a1 = a.transpose(1, 3).contiguous().reshape(4, 3*32*32).reshape(4, 32, 32, 3).transpose(1, 3)
# transpose 后，由于数据储存格式改变，内存会变得不连续，用 contiguous 使其连续

torch.all(torch.eq(a, a1))  # eq 可以比较两个 tensor 内相同位置元素是否相等，all 用来判断括号内是否所以 evaluate 都为 true

tensor(True)

### permute

In [14]:
a = torch.rand([28, 28, 3, 4])

a.permute(3, 2, 0, 1).shape  # 

torch.Size([4, 3, 28, 28])

## 合并与分割

In [15]:
a = torch.rand([5, 32, 8])
b = torch.rand([4, 32, 8])

torch.cat([a, b], dim=0).shape  # cat 可以将两个 tensor 合并，dim 指定在哪个维度进行合并

torch.Size([9, 32, 8])

In [16]:
a = torch.rand([32, 32])
b = torch.rand([32, 32])

torch.stack([a, b], dim=0).shape  # stack 也是将 tensor 合并，但会在前面增加一个新的维度

torch.Size([2, 32, 32])

In [18]:
a = torch.rand([3, 32, 8])

x = a.split(1, dim=0)  # split 可以将 tensor 拆分，左边是在维度 0 上进行拆分，每个拆分后的 tensor 0 维度为 1
x[0].shape, x[1].shape, x[2].shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

In [19]:
a = torch.rand([3, 32, 8])

x = a.split([1, 2], dim=0)  # split 的另一种用法，在维度 0 上进行拆分，按 [1, 2] 的比例拆
x[0].shape, x[1].shape

(torch.Size([1, 32, 8]), torch.Size([2, 32, 8]))

In [20]:
a = torch.rand([3, 32, 8])

x = a.chunk(2, dim=0)  # chunk 是按数量来拆分，2 意为拆成两个
x[0].shape, x[1].shape

(torch.Size([2, 32, 8]), torch.Size([1, 32, 8]))

## 数学运算

### 低维 加减乘除

In [21]:
a = torch.rand(3, 4)
b = torch.rand(4)

In [22]:
a + b, torch.add(a, b)  # 以下都是相同位置的元素互相进行运算

(tensor([[0.7902, 1.2367, 1.0963, 0.8027],
         [0.9721, 1.1580, 1.7847, 0.4547],
         [0.9436, 0.9703, 1.3344, 0.2798]]),
 tensor([[0.7902, 1.2367, 1.0963, 0.8027],
         [0.9721, 1.1580, 1.7847, 0.4547],
         [0.9436, 0.9703, 1.3344, 0.2798]]))

In [23]:
a - b, torch.sub(a, b)

(tensor([[ 0.2212,  0.1102, -0.7583,  0.3798],
         [ 0.4031,  0.0315, -0.0700,  0.0318],
         [ 0.3746, -0.1562, -0.5202, -0.1431]]),
 tensor([[ 0.2212,  0.1102, -0.7583,  0.3798],
         [ 0.4031,  0.0315, -0.0700,  0.0318],
         [ 0.3746, -0.1562, -0.5202, -0.1431]]))

In [24]:
a * b, torch.mul(a, b)

(tensor([[0.1439, 0.3793, 0.1567, 0.1250],
         [0.1956, 0.3350, 0.7950, 0.0514],
         [0.1875, 0.2293, 0.3775, 0.0144]]),
 tensor([[0.1439, 0.3793, 0.1567, 0.1250],
         [0.1956, 0.3350, 0.7950, 0.0514],
         [0.1875, 0.2293, 0.3775, 0.0144]]))

In [25]:
a / b, torch.div(a, b)

(tensor([[1.7774, 1.1957, 0.1823, 2.7961],
         [2.4167, 1.0559, 0.9245, 1.1504],
         [2.3166, 0.7227, 0.4390, 0.3231]]),
 tensor([[1.7774, 1.1957, 0.1823, 2.7961],
         [2.4167, 1.0559, 0.9245, 1.1504],
         [2.3166, 0.7227, 0.4390, 0.3231]]))

### matmul

In [29]:
a = torch.tensor([[3., 3.], [3., 3.]])
b = torch.ones(2, 2)

a, b

(tensor([[3., 3.],
         [3., 3.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [30]:
a * b, a @ b, torch.mm(a, b), torch.matmul(a, b)  # 后三个都是矩阵运算，推荐使用 matmul

(tensor([[3., 3.],
         [3., 3.]]),
 tensor([[6., 6.],
         [6., 6.]]),
 tensor([[6., 6.],
         [6., 6.]]),
 tensor([[6., 6.],
         [6., 6.]]))

In [31]:
a = torch.rand([4, 3, 28, 64])
b = torch.rand([4, 3, 64, 32])

torch.matmul(a, b).shape  # 对于多 tensor，只计算后两维

torch.Size([4, 3, 28, 32])

In [32]:
a = torch.rand([4, 3, 28, 64])
b = torch.rand([4, 1, 64, 32])  # broadcast => [4, 3, 64, 32]

torch.matmul(a, b).shape  # broadcast 的应用

torch.Size([4, 3, 28, 32])

### 平方 & 开方

In [39]:
a = torch.full([2, 2], 9.)

a

tensor([[9., 9.],
        [9., 9.]])

In [40]:
a.pow(2), a ** 2

(tensor([[81., 81.],
         [81., 81.]]),
 tensor([[81., 81.],
         [81., 81.]]))

In [41]:
a.sqrt(), a ** 0.5

(tensor([[3., 3.],
         [3., 3.]]),
 tensor([[3., 3.],
         [3., 3.]]))

In [43]:
a.rsqrt()  # rsqrt() 是取平方根后再取倒数，9 ** 0.5 = 3， 1 / 3 = 0.3333

(tensor([[9., 9.],
         [9., 9.]]),
 tensor([[0.3333, 0.3333],
         [0.3333, 0.3333]]))

### 指数和对数

In [44]:
a = torch.ones(2, 2)
torch.exp(a)  # exp 表示 e 的指数，e ^ 1 = e = 2.7183

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [46]:
a = torch.exp(torch.ones(2, 2))

torch.log(a)  # log(a) 是以 e 为底的 a 的对数

tensor([[1., 1.],
        [1., 1.]])

In [47]:
a = torch.full([2, 2], 8.)
b = torch.full([2, 2], 2.)

torch.log(a) / torch.log(b)  # 要想求以其他数为底的对数，loga b / loga c = logc b, 8 = 2 ^ 3

tensor([[3., 3.],
        [3., 3.]])

### approximation

In [49]:
a = torch.tensor(3.14)

a.floor(), a.ceil(), a.trunc(), a.frac(), a.round()  
# floor：向下取整，ceil：向上取整，trunc：取整数部分，frac：取小数部分, round：四舍五入

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400), tensor(3.))

### clamp

主要用于对梯度裁剪

In [53]:
grad = torch.rand([2, 3]) * 15  # 放大 15 倍

grad, grad.max(), grad.median()  # 最大值 和 中位数

(tensor([[ 9.3713,  5.5154, 10.2777],
         [ 9.5479,  8.3216,  6.8333]]),
 tensor(10.2777),
 tensor(8.3216))

In [54]:
grad.clamp(10)  # 限定最小值为 10

tensor([[10.0000, 10.0000, 10.2777],
        [10.0000, 10.0000, 10.0000]])

In [56]:
grad.clamp(0, 10)  # 限制在 0 ~ 10

tensor([[ 9.3713,  5.5154, 10.0000],
        [ 9.5479,  8.3216,  6.8333]])