In [2]:
import torch

## 数据类型

In [6]:
# 类型
a = torch.randn(2, 3)  # shape is [2, 3]

print(a.type())
print(type(a))
print(isinstance(a, torch.FloatTensor))

torch.FloatTensor
<class 'torch.Tensor'>
True


In [7]:
print(isinstance(a, torch.cuda.FloatTensor))  # 数据是 cpu 类型的

a = a.cuda()  # 把数据变为 gpu 类型
print(isinstance(a, torch.cuda.FloatTensor))

False
True


### 标量

In [8]:
a = torch.tensor(1)
print(a)

b = torch.tensor(1.300)
print(b)

tensor(1)
tensor(1.3000)


### 看 dim
dim 和 shape 的区别：一个 [2, 3] 的 tensor，它的 shape 是 (2, 3)，它的 dim 是 2.

In [12]:
a = torch.tensor(2.5)
a.shape, len(a.shape), a.size()

(torch.Size([]), 0, torch.Size([]))

In [13]:
a = torch.randn(2, 3)
a.shape, len(a.shape), a.size()

(torch.Size([2, 3]), 2, torch.Size([2, 3]))

In [15]:
a = torch.tensor([2.3, 1.])
a, a.shape, len(a.shape), a.size()

(tensor([2.3000, 1.0000]), torch.Size([2]), 1, torch.Size([2]))

In [17]:
b = torch.FloatTensor([1])
c = torch.FloatTensor([2, 3])

b, c

(tensor([1.]), tensor([2., 3.]))

In [18]:
import numpy as np

data = np.ones(2)

a = torch.from_numpy(data)

data, a

(array([1., 1.]), tensor([1., 1.], dtype=torch.float64))

In [19]:
a = torch.ones(2)
a

tensor([1., 1.])

In [20]:
a = torch.zeros(2)
a

tensor([0., 0.])

In [22]:
# shape 和 size 都可以索引
a = torch.rand([2, 3])  # rand 和 randn，随机均匀分布，和随机正态分布

a, a.shape[0], a.shape[1], a.size(0), a.size(1)

(tensor([[0.8822, 0.4626, 0.6545],
         [0.8265, 0.5604, 0.1371]]),
 2,
 3,
 2,
 3)

In [23]:
# list 可以直接返回一个 list

a = torch.randn([2, 3, 4])
list(a.shape)

[2, 3, 4]

### 得到 tensor 数据的大小

In [27]:
a = torch.randn(2, 3, 28, 28)

a.numel(), a.dim()  # numel() 返回 tensor 占的内存

(4704, 4)

## 创建 tensor

In [28]:
# 从 numpy 中转换

a = np.array([2, 3.3])
b = torch.from_numpy(a)

c = np.ones([2, 3])
d = torch.from_numpy(c)

b, d

(tensor([2.0000, 3.3000], dtype=torch.float64),
 tensor([[1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64))

In [29]:
# 从 list 中转换

list = [2, 3, 4]
a = torch.tensor(list)

a

tensor([2, 3, 4])

### 创建未初始化的 tensor

In [30]:
a = torch.empty([2, 3])
a

tensor([[6.7406e+22, 2.6540e-09, 2.0804e+23],
        [1.6764e+22, 6.7703e+22, 5.4883e-05]])

### 创建随机 tensor

In [32]:
a = torch.randn([3, 2, 5])

b = torch.rand_like(a)

b.shape

torch.Size([3, 2, 5])

In [33]:
a = torch.randint(1, 10, [3, 3])  # 生成的 tensor 范围：[1, 10), shape 为 [3, 3]

a

tensor([[9, 9, 9],
        [2, 2, 9],
        [4, 2, 5]])

In [39]:
# 自定义均值和方差

a = torch.normal(mean=torch.full([10], 0.), std=torch.arange(1, 0., -0.1))
a

tensor([ 0.9925, -0.9006, -0.5114, -0.4418, -0.3699, -0.0488,  0.5707, -0.5671,
        -0.1098, -0.0755])

### torch.full

In [40]:
torch.full([2, 3], 5)  # 把 tensor 全赋值为 5

tensor([[5, 5, 5],
        [5, 5, 5]])

In [41]:
torch.full([], 7.)

tensor(7.)

### torch.arange

In [42]:
a = torch.arange(1, 10)
b = torch.arange(1, 10, 2)

a, b

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 3, 5, 7, 9]))

### linspace/logspace

In [44]:
a = torch.linspace(0, 10, steps=4)  # 把 1~10 分为 4 份
b = torch.linspace(0, 10, steps=11)

a, b

(tensor([ 0.0000,  3.3333,  6.6667, 10.0000]),
 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [50]:
a = torch.logspace(0, 1, steps=10)  # 把 0~1 分为 10 份，然后返回 10^i
b = torch.logspace(0, -1, steps=10)

a, b

(tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
          7.7426, 10.0000]),
 tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
         0.1000]))

### ones, zeros, eye

In [52]:
torch.ones([3, 3]), torch.zeros([2, 3])

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [55]:
torch.eye(2, 3), torch.eye(3)  # 对角线是 1

(tensor([[1., 0., 0.],
         [0., 1., 0.]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

### 随机打散

In [56]:
torch.randperm(10)

tensor([4, 3, 5, 7, 9, 0, 2, 1, 8, 6])

## tensor 索引与切片